---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "cinder-api"
    - "cinder-backup"
    - "cinder-scheduler"
    - "cinder-volume"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "cinder-api"
    - "cinder-backup"
    - "cinder-scheduler"
    - "cinder-volume"

- name: Copying over cinder.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/cinder.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/cinder.conf"
      - "/etc/kolla/config/cinder/{{ item }}.conf"
    dest: "{{ node_config_directory }}/{{ item }}/cinder.conf"
  register: cinder_config
  when: inventory_hostname in groups[item]
  notify:
      - restart cinder services
  with_items:
    - "cinder-api"
    - "cinder-backup"
    - "cinder-scheduler"
    - "cinder-volume"

# NOTE(qiuyu): avoid unnecessary restart in initial setup
- meta: flush_handlers
